
package prematriculaClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PrematriculasControl", targetNamespace = "http://control.prematriculas.unicauca.edu.co/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PrematriculasControl {


    /**
     * 
     * @param arg0
     * @return
     *     returns co.edu.unicauca.prematriculas.control.Estudiante
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cargarDatosEstudiante", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarDatosEstudiante")
    @ResponseWrapper(localName = "cargarDatosEstudianteResponse", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarDatosEstudianteResponse")
    public Estudiante cargarDatosEstudiante(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.edu.unicauca.prematriculas.control.Nota>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cargarHistoriaAcademica", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarHistoriaAcademica")
    @ResponseWrapper(localName = "cargarHistoriaAcademicaResponse", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarHistoriaAcademicaResponse")
    public List<Nota> cargarHistoriaAcademica(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns co.edu.unicauca.prematriculas.control.Docente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cargarDatosDocente", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarDatosDocente")
    @ResponseWrapper(localName = "cargarDatosDocenteResponse", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarDatosDocenteResponse")
    public Docente cargarDatosDocente(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.edu.unicauca.prematriculas.control.MateriaPensum>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cargarPensum", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarPensum")
    @ResponseWrapper(localName = "cargarPensumResponse", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarPensumResponse")
    public List<MateriaPensum> cargarPensum(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.edu.unicauca.prematriculas.control.ProgramaEstudiante>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cargarProgramasEstudiante", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarProgramasEstudiante")
    @ResponseWrapper(localName = "cargarProgramasEstudianteResponse", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarProgramasEstudianteResponse")
    public List<ProgramaEstudiante> cargarProgramasEstudiante(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<co.edu.unicauca.prematriculas.control.MateriaEquivalente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cargarMateriasEquivalentesEstudiante", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarMateriasEquivalentesEstudiante")
    @ResponseWrapper(localName = "cargarMateriasEquivalentesEstudianteResponse", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", className = "co.edu.unicauca.prematriculas.control.CargarMateriasEquivalentesEstudianteResponse")
    public List<MateriaEquivalente> cargarMateriasEquivalentesEstudiante(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
