
package prematriculaClient;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrematriculasControlService", targetNamespace = "http://control.prematriculas.unicauca.edu.co/", wsdlLocation = "http://10.200.1.57:8080/prematricula/PrematriculasControl?wsdl")
public class PrematriculasControlService
    extends Service
{

    private final static URL PREMATRICULASCONTROLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PREMATRICULASCONTROLSERVICE_EXCEPTION;
    private final static QName PREMATRICULASCONTROLSERVICE_QNAME = new QName("http://control.prematriculas.unicauca.edu.co/", "PrematriculasControlService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.200.1.57:8080/prematricula/PrematriculasControl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PREMATRICULASCONTROLSERVICE_WSDL_LOCATION = url;
        PREMATRICULASCONTROLSERVICE_EXCEPTION = e;
    }

    public PrematriculasControlService() {
        super(__getWsdlLocation(), PREMATRICULASCONTROLSERVICE_QNAME);
    }

    public PrematriculasControlService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PREMATRICULASCONTROLSERVICE_QNAME, features);
    }

    public PrematriculasControlService(URL wsdlLocation) {
        super(wsdlLocation, PREMATRICULASCONTROLSERVICE_QNAME);
    }

    public PrematriculasControlService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PREMATRICULASCONTROLSERVICE_QNAME, features);
    }

    public PrematriculasControlService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrematriculasControlService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrematriculasControl
     */
    @WebEndpoint(name = "PrematriculasControlPort")
    public PrematriculasControl getPrematriculasControlPort() {
        return super.getPort(new QName("http://control.prematriculas.unicauca.edu.co/", "PrematriculasControlPort"), PrematriculasControl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrematriculasControl
     */
    @WebEndpoint(name = "PrematriculasControlPort")
    public PrematriculasControl getPrematriculasControlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://control.prematriculas.unicauca.edu.co/", "PrematriculasControlPort"), PrematriculasControl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PREMATRICULASCONTROLSERVICE_EXCEPTION!= null) {
            throw PREMATRICULASCONTROLSERVICE_EXCEPTION;
        }
        return PREMATRICULASCONTROLSERVICE_WSDL_LOCATION;
    }

}
